* cl-ses - Send emails from Common Lisp with AWS's SES

  cl-ses is a simple, low footprint, Common Lisp package for sending
  email with AWS's SES.

** Usage
   cl-ses exports one simple =send-email= function:

   #+BEGIN_SRC lisp
     (cl-ses:send-email :from "me@example.com"
                        :to "you@example.com"
                        :subject "Hello from CL-SES"
                        :message "The body of the email message"
                        :aws-access-key "XXXXXX"
                        :aws-secret-key "XXXXXXXXXXX")
   #+END_SRC

   =send-email= returns =T= if the status was 200 (OK), and =NIL=
   otherwise. In the future I'll hopefully have implemented better
   error reporting.

*** Setting the Content-Type
    There is support for setting the email's =Content-Type=. I've
    tested with =text/plan= and =text/html=, which both work and I'm
    sure others do as well:

   #+BEGIN_SRC lisp
     (cl-ses:send-email ...
                        ...
                        :content-type "text/html"
                        ...)
   #+END_SRC

    The content-type key is optional, and defaults to =text/plain=.

*** Using a name in the from field
    When sending emails, you can set a name to be shown in the =from=
    parameter. This is not AWS specific, but I believe most modern
    email clients will parse it OK:

   #+BEGIN_SRC lisp
     (cl-ses:send-email :from "My Name <me@example.com>"
                        ...
                        ...)
   #+END_SRC


** Dependencies
   - [[http://weitz.de/drakma/][Drakma]] is the only external dependency

** Installation
   Right now this is only on GitHub, but if you use quicklisp it's
   still easy to include in a project:

   =git clone git@github.com:CodyReichert/cl-ses ~/quicklisp/local-projects=

   then you can:

   =(ql:quickload :cl-ses)=

** Author

+ Cody Reichert (codyreichert@gmail.com)

** Copyright

Copyright (c) 2015 Cody Reichert (codyreichert@gmail.com)
